language: python
python:
  - "2.7"
install: pip install -r requirements.txt -r test-requirements.txt
script: nosetests .
notifications:
  email:
    recipients:
      - dev+tests-reports@proformatique.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
