sync:
  image: n3llyb0y/wait
  links:
    - ari
    - ctid-ng
    - rabbitmq
  environment:
    PORTS: "5039 5672 9500"
    TIMEOUT: "5"

ari:
  image: ari-mock
  expose:
    - "5039"
  volumes:
    - "./ari:/usr/local/share/ari"
    - "./ssl:/usr/local/share/ssl"
  environment:
    PYTHONPATH: "/usr/local/share/ari"
  command: "gunicorn -b 0.0.0.0:5039 -k flask_sockets.worker mock_ari:app"

ctid-ng:
  image: xivo-ctid-ng-test
  volumes:
    - "../../..:/usr/src/xivo-ctid-ng"
    - "./etc/xivo-ctid-ng:/etc/xivo-ctid-ng"
    - "./ssl:/usr/local/share/ssl"
  ports:
    - "9500:9500"
  links:
    - ari
    - rabbitmq

rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"
