sync:
  image: n3llyb0y/wait
  links:
    - auth
    - ari
    - confd
    - ctid-ng
    - rabbitmq
  environment:
    PORTS: "5039 5040 5672 9486 9497 9500"
    TIMEOUT: "5"

ari:
  image: quintana/asterisk
  ports:
    - "5039:5039"
  volumes:
    - "./etc/asterisk:/etc/asterisk"
    - "./ssl:/usr/local/share/ssl"
  command: "asterisk -fvvv"

auth:
  image: p0bailey/docker-flask
  volumes:
    - "./xivo-auth:/usr/local/share/xivo-auth"
    - "./ssl:/usr/local/share/ssl"
  command: "python /usr/local/share/xivo-auth/mock-xivo-auth.py 9497"

confd:
  image: p0bailey/docker-flask
  volumes:
    - "./xivo-confd:/usr/local/share/xivo-confd"
    - "./ssl:/usr/local/share/ssl"
  command: "python /usr/local/share/xivo-confd/mock-xivo-confd.py 9486"

ctid-ng:
  image: xivo-ctid-ng-test
  volumes:
    - "../../..:/usr/src/xivo-ctid-ng"
    - "./etc/xivo-ctid-ng:/etc/xivo-ctid-ng"
    - "./ssl:/usr/local/share/ssl"
  ports:
    - "9500:9500"
  links:
    - ari
    - auth
    - confd
    - rabbitmq

rabbitmq:
  image: rabbitmq
