extra_config_files: /etc/xivo-ctid-ng/conf.d/

debug: false
logfile: /var/log/xivo-ctid-ng.log
pidfile: /var/run/xivo-ctid-ng.pid

rest_api:
  listen: 0.0.0.0
  port: 9500
  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key
  cors:
    enabled: True
    allow_headers: Content-Type, X-Auth-Token

auth:
  host: auth
  port: 9497
  timeout: 2
  verify_certificate: /usr/share/xivo-certs/server.crt
  key_file: /etc/xivo-ctid-ng/key.yml

ari:
  connection:
    base_url: http://ari:5039
    username: xivo
    password: Nasheow8Eag

bus:
  username: guest
  password: guest
  host: rabbitmq
  port: 5672
